language: cpp
os:
- linux

compiler:
- g++
- clang++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise
    packages:
    - g++-5
    - gcc-5
    - clang-3.7

install:
    - sudo apt-get -qq update;
    - sudo apt-get -qq install libboost1.48-all-dev;

script:
    - cmake .; make; make test;
