title = "sample"

[table] # this is sample.
boolean           = true
integer           = -100_000
float             = +1.38e-23
basic_string      = "basic \"string\""
multi_line_string = """
    multi line
    string
    \u00CB\u015C\u010C
    """
array          = [1, 2, 3]
array_of_array = [[1, 2], # this is comment.
                  [3], [4,5,6]]
inline_table   = {a = true, b = "string", c = ["a", "r", "r", "a", "y"]}
inline_array_of_table = [
    {id = 1},
    {id = 2},
    {id = 3},
    {id = 4}
]

[table2]
basic_string = "you can define same key in different table"

[[array_of_table]]
index = 1
[[array_of_table]]
index = 2
[[array_of_table]]
index = 3
